apiVersion: v1
kind: Pod
metadata:
  name: openebs-ds-pod

spec:
  hostNetwork: true

  containers:
  - image: satyamz/docker-jupyter:v0.4
    name: docker-jupyter
    env:
    - name: GIT_REPO
      value: https://github.com/vharsh/plot-demo.git
    ports:
      - containerPort: 8888
        hostPort: 8888
    volumeMounts:
      - name: demo-vol1
        mountPath: /mnt/data
  volumes:
  - name: demo-vol1
    persistentVolumeClaim:
      claimName: demo-vol1-claim
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: demo-vol1-claim
spec:
  storageClassName: openebs-basic
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
